
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.44.1'
version_full = 'e5aad2df9cba1133bdbf830594413f17f662b00e'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

